os: osx
language: bash
install:
  - brew update
  - brew tap nrobinson2000/NewPo
  - brew install po
  - ./config-expect.sh
  - po install
script:
  - po init test && cd test
  - po photon build
  - po electron clean
  - po electron build
  - po P1 clean
  - po P1 build
  - po core clean
  - po core build
